---
title: "naniar"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Package 'naniar'
November 20, 2018
Type Package
Title Data Structures, Summaries, and Visualisations for Missing Data
Version 0.4.1

####  Description 
 Missing values are ubiquitous in data and need to be explored and
handled in the initial stages of analysis. 'naniar' provides data structures
and functions that facilitate the plotting of missing values and examination
of imputations. This allows missing data dependencies to be explored with
minimal deviation from the common work patterns of 'ggplot2' and tidy data.
License MIT + file LICENSE
LazyData TRUE
ByteCompile TRUE
Suggests knitr, rmarkdown, testthat, rpart, rpart.plot, covr,
gridExtra, wakefield, vdiffr, here, simputation, imputeTS,
gdtools, Hmisc
VignetteBuilder knitr
Depends R (>= 3.1.2)
Imports dplyr, ggplot2, purrr, tidyr, tibble, magrittr, stats, visdat,
rlang, forcats, viridis, glue, UpSetR
Collate 'add-cols.R' 'add-n-prop-miss.R' 'cast-shadows.R'
'data-common-na-numbers.R' 'data-common-na-strings.R'
'data-oceanbuoys.R' 'data-pedestrian.R' 'data-riskfactors.R'
'legend-draw.R' 'geom-miss-point.R' 'gg-miss-case-cumsum.R'
'gg-miss-case.R' 'gg-miss-fct.R' 'gg-miss-span.R'
'gg-miss-upset.R' 'gg-miss-var-cumsum.R' 'gg-miss-var.R'
'gg-miss-which.R' 'helpers.R' 'impute-median.R'
'impute_below.R' 'impute_mean.R' 'label-miss.R'
'miss-complete-x-pct-prop.R' 'miss-prop-pct-summary.R'
'miss-scan-count.R' 'miss-x-cumsum.R' 'miss-x-run.R'
'miss-x-span.R' 'miss-x-summary.R' 'miss-x-table.R'
'n-prop-miss-complete-rows.R' 'n-prop-miss-complete.R'
'n-var-miss.R' 'nabular.R' 'naniar-ggproto.R'
'naniar-package.R' 'prop-pct-var-case-miss-complete.R'
'replace-to-na.R' 'replace-with-na.R'
1
2 R topics documented:
'scoped-replace-with-na.R' 'shade.R' 'shadow-recode.R'
'shadow-shifters.R' 'shadow-verifiers.R' 'shadows.R'
'stat-miss-point.R' 'utils.R' 'where-na.R'
URL https://github.com/njtierney/naniar
BugReports https://github.com/njtierney/naniar/issues
Encoding UTF-8
RoxygenNote 6.1.1
NeedsCompilation no
Author Nicholas Tierney [aut, cre] (<https://orcid.org/0000-0003-1460-8722>),
Di Cook [aut] (<https://orcid.org/0000-0002-3813-7155>),
Miles McBain [aut] (<https://orcid.org/0000-0003-2865-2548>),
Colin Fay [aut] (<https://orcid.org/0000-0001-7343-1846>),
Mitchell O'Hara-Wild [ctb],
Jim Hester [ctb],
Luke Smith [ctb]
Maintainer Nicholas Tierney <nicholas.tierney@gmail.com>
Repository CRAN
Date/Publication 2018-11-20 08:20:09 UTC
R topics documented:
add_any_miss 5
add_label_missings . 6
add_label_shadow . . 7
add_miss_cluster . . 8
add_n_miss . 8
add_prop_miss . . . 9
add_shadow . 10
add_shadow_shift . . 11
add_span_counter . . 12
all-is-miss-complete . 13
all_row_complete . . 13
all_row_miss 14
any-na 14
any_row_miss 15
as_shadow . . 15
as_shadow.data.frame 16
as_shadow_upset . . 16
bind_shadow 17
cast_shadow . 18
cast_shadow_shift . . 19
cast_shadow_shift_label . . 20
common_na_numbers 21
common_na_strings . 22
R topics documented: 3
gather_shadow . . . 23
GeomMissPoint . . . 23
geom_miss_point . . 24
gg_miss_case 25
gg_miss_case_cumsum . . . 26
gg_miss_fct . 27
gg_miss_span 28
gg_miss_upset 29
gg_miss_var . 30
gg_miss_var_cumsum . . . 31
gg_miss_which . . . 31
group_by_fun 32
impute_below 33
impute_below_all . . 33
impute_below_at . . 34
impute_below_if . . 35
impute_mean 36
impute_median . . . 37
is_shade . . . 38
is_shadow . . 39
label_missings 39
label_miss_1d 40
label_miss_2d 41
label_shadow 42
miss-complete-case-pct . . . 42
miss-complete-case-prop . . 43
miss-complete-var-pct . . . 43
miss-complete-var-prop . . . 44
miss_case_summary 45
miss_case_table . . . 46
miss_prop_summary 46
miss_scan_count . . 47
miss_summary . . . 48
miss_var_run 49
miss_var_span 50
miss_var_summary . 52
miss_var_table . . . 53
miss_var_which . . . 54
n-var-case-complete . 54
n-var-case-miss . . . 55
nabular . . . 56
naniar 57
new_nabular . 57
new_shade . . 58
new_shadow . 58
n_complete . 59
n_complete_row . . . 59
n_miss 60
4 R topics documented:
n_miss_row . 61
oceanbuoys . 61
pct-miss-complete-case . . . 63
pct-miss-complete-var . . . 64
pct_complete 65
pct_miss . . . 65
pedestrian . . 66
prop-miss-complete-case . . 67
prop-miss-complete-var . . . 68
prop_complete . . . 69
prop_complete_row . 69
prop_miss . . 70
prop_miss_row . . . 71
recode_shadow . . . 71
replace_to_na 72
replace_with_na . . . 73
replace_with_na_all . 74
replace_with_na_at . 75
replace_with_na_if . 76
riskfactors . . 77
scoped-impute_mean 80
scoped-impute_median . . . 81
shade 83
shadow_expand_relevel . . . 83
shadow_long 84
shadow_shift 85
shadow_shift.numeric 86
stat_miss_point . . . 86
test_if_dataframe . . 87
test_if_missing . . . 88
test_if_null . 89
test_if_shadow . . . 89
unbinders . . 90
update_shadow . . . 91
what_levels . 92
where 92
where_na . . 93
which_are_shade . . 94
which_na . . 94
Index 96
add_any_miss 5
