add_prop_miss Add column containing proportion of missing data values

####  Description 

It can be useful when doing data analysis to add the proportion of missing data values into your dataframe. add_prop_miss adds a column named "prop_miss", which contains the proportion of
missing values in that row. You can specify the variables that you would like to show the missingness
for.

####  Usage 
<pre><code>

add_prop_miss(data, ..., label = "prop_miss")
</code></pre>
#### Arguments 

* ``data``:  a dataframe
... Variable names to use instead of the whole dataset. By default this looks at the whole dataset. Otherwise, this is one or more unquoted expressions separated
by commas. These also respect the dplyr verbs starts_with, contains, ends_with, etc. By default will add "_all" to the label if left blank, otherwise
will add "_vars" to distinguish that it has not been used on all of the variables.
label character string of what you need to name variable

#### Value 

a dataframe

#### See Also 

bind_shadow() add_any_miss() add_label_missings() add_label_shadow() add_miss_cluster()
add_prop_miss() add_shadow_shift() cast_shadow()

#### Examples 
```{r}

airquality %>% add_prop_miss()
airquality %>% add_prop_miss(Solar.R)
airquality %>% add_prop_miss(Solar.R, Ozone)
airquality %>% add_prop_miss(Solar.R, Ozone, label = "testing")
# this can be applied to model the proportion of missing data
# as in Tierney et al bmjopen.bmj.com/content/5/6/e007450.full
library(rpart)
library(rpart.plot)
airquality %>%
add_prop_miss() %>%
rpart(prop_miss_all ~ ., data = .) %>%
prp(type = 4,
extra = 101,
prefix = "prop_miss = ")
```
