
add_n_miss Add column containing number of missing data values

####  Description 

It can be useful when doing data analysis to add the number of missing data points into your
dataframe. add_n_miss adds a column named "n_miss", which contains the number of missing
values in that row.
9

####  Usage 
<pre><code>

add_n_miss(data, ..., label = "n_miss")
</code></pre>
#### Arguments 

* ``data``:  a dataframe
... Variable names to use instead of the whole dataset. By default this looks at
the whole dataset. Otherwise, this is one or more unquoted expressions separated
by commas. These also respect the dplyr verbs starts_with, contains,
ends_with, etc. By default will add "_all" to the label if left blank, otherwise
will add "_vars" to distinguish that it has not been used on all of the variables.
label character default is "n_miss".

#### Value 

a dataframe

#### See Also 

bind_shadow() add_any_miss() add_label_missings() add_label_shadow() add_miss_cluster()
add_prop_miss() add_shadow_shift() cast_shadow()

#### Examples 
```{r}

airquality %>% add_n_miss()
airquality %>% add_n_miss(Ozone, Solar.R)
airquality %>% add_n_miss(dplyr::contains("o"))
```
