miss_var_span Summarise the number of missings for a given repeating span on a variable


####  Description 

To summarise the missing values in a time series object it can be useful to calculate the number of missing values in a given time period. miss_var_span takes a data.frame object, a variable, and
a span_every argument and returns a dataframe containing the number of missing values within each span.

####  Usage 
<pre><code>

miss_var_span(data, var, span_every)
</code></pre>
#### Arguments 

* ``data``: data.frame
* var bare unquoted variable name of interest.
* span_every integer describing the length of the span to be explored

#### Value 

dataframe with variables n_miss, n_complete, prop_miss, and prop_complete, which describe
the number, or proportion of missing or complete values within that given time span.

#### See Also 

pct_miss_case() prop_miss_case() pct_miss_var() prop_miss_var() pct_complete_case()
prop_complete_case() ``pct_complete_var()``,``prop_complete_var()``, miss_prop_summary() miss_
case_summary ``miss_var_table``, ``n_complete``, ``n_complete_row`` miss_var_run miss_var_span
miss_var_summary miss_var_table

#### Examples 
```{r}

miss_var_span(data = pedestrian,
var = hourly_counts,
span_every = 168)
library(dplyr)
pedestrian %>%
group_by(month) %>%
miss_var_span(var = hourly_counts,
span_every = 168)
```
